## NumPy Library

#### NumPy Numerical Python is an open source Python library that's used in almost every field of science and engineering. It's the universal standard for working with numerical data in Python, and it's at the core of the scientific Python and PyData ecosystems.
- The NumPy library contains a multidimensional array and matrix data structures.
- In Python we have lists that serve the purpose fo arrays, but they slow to processk Numpy aims to provide an array object that is up to 50x faster than traditional Python list.
- The array object in NumPy is called ndarray, it provides a lot of supporting finctions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.
- Numpy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently, This behavior is called locality of reference in computer science, This is the main reason why NumPy is faster than lists.
- installation -> pip install numpy
- import   ->  import numpy as np

In [2]:
# importing numpy

import numpy as np

In [3]:
# creating numpy array using list  -> the result type shows numpy ndarray

arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# creating numpy array using tuple  -> the result type shows numpy ndarray

arr= np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimensions in array

In [7]:
arr= np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)   # check dimension by .ndim

20
<class 'numpy.ndarray'>
0


### 1D array

In [8]:
arr= np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


### 2D array

In [9]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [10]:
# floting numbers 

arr= np.array([[1.2,2.3,3.4],[5.6,6.7,7.8]])
print(arr)
print(arr.ndim)

[[1.2 2.3 3.4]
 [5.6 6.7 7.8]]
2


### 3D array

In [11]:
arr= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [16]:
# make all dimensions 

a= np.array(34)
b= np.array([1,2,3,4])
c= np.array([[1,2,3,4],[5,6,7,8]])
d= np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

print("a=", a.ndim)
print('b=', b.ndim)
print('c=', c.ndim)
print('d=', d.ndim)


a= 0
b= 1
c= 2
d= 3


#### Create an array with 5 dimensions and verify that it has 5 dimensions:

In [21]:
# another method to create dimensions by -> ndmin=

arr= np.array([1,2,3,4,5], ndmin=5) # it shows 5D array
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


## NumPy Array Indexing
- Array indexing is the same as accessing an array element.
- You can access an array element by referring to its index number.
- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [23]:
# Get the first element from the following array:

arr= np.array([1,2,3,4,5,6,7])
print(arr[0])

1


In [27]:
# more examples:

a= np.array([23,43,67,87,67,56,73,29,58,47,61,30,37])
print('the second element is:', a[2])
print('the fourth element is:', a[4])
print('the sixth element is:', a[6])
print('the eighth element is:', a[8])

the second element is: 67
the fourth element is: 67
the sixth element is: 73
the eighth element is: 58


### Access 2D Arrays
- To access elements from 2D arrays we can use comma separated integers representing the dimension and index of the element.
- Think of 2D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [32]:
# ([[array 0],[array 1]])

arr= np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('2nd element on first row:', arr[0,1])

2nd element on first row: 20


In [31]:
arr= np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('3rd element of 2nd row:',arr[1,2])

3rd element of 2nd row: 80


In [33]:
# Add the third element of row 1 and last element of row 2

arr= np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('sum is:',arr[0,2]+arr[1,4])

sum is: 130


### Access 3D Arrays
- To access elements from 3D arrays we can use comma separated integers representing the dimensions and the index of the element.