## NumPy Library

#### NumPy Numerical Python is an open source Python library that's used in almost every field of science and engineering. It's the universal standard for working with numerical data in Python, and it's at the core of the scientific Python and PyData ecosystems.
- The NumPy library contains a multidimensional array and matrix data structures.
- In Python we have lists that serve the purpose fo arrays, but they slow to processk Numpy aims to provide an array object that is up to 50x faster than traditional Python list.
- The array object in NumPy is called ndarray, it provides a lot of supporting finctions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.
- Numpy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently, This behavior is called locality of reference in computer science, This is the main reason why NumPy is faster than lists.
- installation -> pip install numpy
- import   ->  import numpy as np

In [56]:
# importing numpy

import numpy as np

In [57]:
# creating numpy array using list  -> the result type shows numpy ndarray

arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [58]:
print(type(arr))

<class 'numpy.ndarray'>


In [59]:
# creating numpy array using tuple  -> the result type shows numpy ndarray

arr= np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimensions in array

In [60]:
arr= np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)   # check dimension by .ndim

20
<class 'numpy.ndarray'>
0


### 1D array

In [61]:
arr= np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


### 2D array

In [62]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [63]:
# floting numbers 

arr= np.array([[1.2,2.3,3.4],[5.6,6.7,7.8]])
print(arr)
print(arr.ndim)

[[1.2 2.3 3.4]
 [5.6 6.7 7.8]]
2


### 3D array

In [64]:
arr= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [65]:
# make all dimensions 

a= np.array(34)
b= np.array([1,2,3,4])
c= np.array([[1,2,3,4],[5,6,7,8]])
d= np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

print("a=", a.ndim)
print('b=', b.ndim)
print('c=', c.ndim)
print('d=', d.ndim)


a= 0
b= 1
c= 2
d= 3


#### Create an array with 5 dimensions and verify that it has 5 dimensions:

In [66]:
# another method to create dimensions by -> ndmin=

arr= np.array([1,2,3,4,5], ndmin=5) # it shows 5D array
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


## NumPy Array Indexing
- Array indexing is the same as accessing an array element.
- You can access an array element by referring to its index number.
- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [67]:
# Get the first element from the following array:

arr= np.array([1,2,3,4,5,6,7])
print(arr[0])

1


In [68]:
# more examples:

a= np.array([23,43,67,87,67,56,73,29,58,47,61,30,37])
print('the second element is:', a[2])
print('the fourth element is:', a[4])
print('the sixth element is:', a[6])
print('the eighth element is:', a[8])

the second element is: 67
the fourth element is: 67
the sixth element is: 73
the eighth element is: 58


### Access 2D Arrays
- To access elements from 2D arrays we can use comma separated integers representing the dimension and index of the element.
- Think of 2D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [69]:
# ([[array 0],[array 1]])

arr= np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('2nd element on first row:', arr[0,1])

2nd element on first row: 20


In [70]:
arr= np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('3rd element of 2nd row:',arr[1,2])

3rd element of 2nd row: 80


In [71]:
# Add the third element of row 1 and last element of row 2

arr= np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('sum is:',arr[0,2]+arr[1,4])

sum is: 130


### Access 3D Arrays
- To access elements from 3D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [72]:
# Access the third element of the second array of the first array:

arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [73]:
arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,2])

12


## Slicing of NumPy arrays

In [74]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [75]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [76]:
# Slicing in 2D array

a= np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [77]:
a= np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[0,0:3])

[10 20 30]


#### Data types in NumPy
##### NumPy has some extra data types, and refer to data types one character, like i for integers,
- i - interger
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type (void)

In [78]:
# Checking the data type of an array

arr= np.array([1,2,3,4])
print(arr.dtype)

int64


In [79]:
arr= np.array(['animals', 'bat', 'cat'])
print(arr.dtype)

<U7


In [80]:
# creating arrays with a defined data type

arr= np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [81]:
# Create an array with data types 4 bytes integer

arr= np.array([1,2,3,4], dtype= 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### NumPy array Shape
#### The shape of an array is the number of elements in each dimension

In [82]:
# Print the shape of a 2D array

arr= np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [83]:
arr= np.array([[[1,2,3,4],[5,6,7,8],[10,20,30,40]]])
print(arr.shape)

(1, 3, 4)


### Joining NumPy Arrays

In [84]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

arr= np.concatenate([arr1, arr2])
print(arr)

[1 2 3 4 5 6]


In [85]:
# Join 2D array (concatenate)

arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])

arr= np.concatenate([arr1,arr2], axis=1) # axis=1 --> is for join row wise
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [86]:
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])

arr= np.concatenate([arr1,arr2], axis=0) # axis=0 --> is for join column wise
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Splitting NumPy arrays

In [87]:
# splitting the array in 3 parts

arr= np.array([1,2,3,4,5,6])

newarr= np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [88]:
# splitting the array in 4 parts

arr= np.array([1,2,3,4,5,6])

newarr= np.array_split(arr,4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


## ravel & flatten
### converts multidimensional array into 1D array

In [89]:
m= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('dimension', m.ndim)

n= m.ravel() # .ravel() --> converts multidimensional arrays into 1D array
print(n)
print('now the new dimension is:', n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is: 1


In [90]:
m= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('dimension', m.ndim)

n= m.flatten() # .flatten() --> converts multidimensional arrays into 1D array (same as .ravel() )
print(n)
print('now the new dimension is:', n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is: 1


In [91]:
c= np.array([[[[1,2,3],[78,89,25],[45,26,84]]]])
print(c)
print('the dimension is:',c.ndim)

d= c.ravel()  # convert into 1D
print(d)
print('now the new dimension is:', d.ndim)


[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]
the dimension is: 4
[ 1  2  3 78 89 25 45 26 84]
now the new dimension is: 1


### Unique Function

In [92]:
k= np.array([12,14,6,7,9,3,4,5,22,33,7,6,1,2,12])
print(k)
x= np.unique(k) # .unique function shows a unique value
print(x)

[12 14  6  7  9  3  4  5 22 33  7  6  1  2 12]
[ 1  2  3  4  5  6  7  9 12 14 22 33]


In [93]:
k= np.array([12,14,6,7,9,3,4,5,22,33,7,6,1,2,12])
print(k)
x= np.unique(k, return_index= True)  # it shows the index position of unique numbers
print(x)

[12 14  6  7  9  3  4  5 22 33  7  6  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 14, 22, 33]), array([12, 13,  5,  6,  7,  2,  3,  4,  0,  1,  8,  9]))


In [94]:
k= np.array([12,14,6,7,9,3,4,5,22,33,7,6,1,2,12])
print(k)
x= np.unique(k, return_index= True, return_counts= True) # return_count --> it shows the number of repeted values 
print(x)

[12 14  6  7  9  3  4  5 22 33  7  6  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 14, 22, 33]), array([12, 13,  5,  6,  7,  2,  3,  4,  0,  1,  8,  9]), array([1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1]))


### Delete

In [95]:
a= np.array([12,13,14,15])
d= np.delete(a,[1])
print(d)

[12 14 15]


In [96]:
x= np.array([[2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
print(x)

m= np.delete(x,1,axis= 0) # axis= 0 --> to delete the row
print()
print(m)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]

[[ 2  7  9  6  8]
 [50  0 65  6  7]]
